version: '3.8'

services:
  # --- MySQL ---
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${PORT_DB_EXTERNAL}:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - smartlyra-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # --- (phpMyAdmin) ---
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "${PORT_PMA_EXTERNAL}:80"
    environment:
      PMA_HOST: ${DB_HOST}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - db
    networks:
      - smartlyra-network

  # --- BACKEND ---
  backend:
    build: ./backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "${PORT_BACKEND_EXTERNAL}:8000"
    volumes:
      - ./backend:/code
    environment:
      DATABASE_URL: mysql+mysqlconnector://${DB_USER}:${DB_PASSWORD}@${DB_HOST}/${DB_NAME}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - smartlyra-network

  # --- FRONTEND ---
  frontend:
    build: ./frontend
    ports:
      - "${PORT_FRONTEND_EXTERNAL}:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_PORT=0
    depends_on:
      - backend
    networks:
      - smartlyra-network

volumes:
  db_data:

networks:
  smartlyra-network:
    driver: bridge